### ISSUE TITLE
Responsive design is not working

### ISSUE THREAD

**Issue by jdnichollsc** [definev/flutterBird#1]

**Comment by definev** [comment]
I followed the ratio on the phone so it was not very responsive, but thank a lot you for reviewing ^.^!!!

**Comment by jdnichollsc** [comment]
![image](https://user-images.githubusercontent.com/2154886/82127419-f3c70e80-9778-11ea-9bb4-32301ef4c9f7.png)

**Comment by definev** [comment]
![image](https://user-images.githubusercontent.com/62325868/82591934-487be680-9bca-11ea-98d1-d1faaaf9b4bf.png)
Hmm probably because of your browser

**Comment by jdnichollsc** [comment]
try resizing horizontally 😅
